#1.1 Importing our libraries

In [36]:
import pandas as pd
import numpy as np

#1.2 Loading our dataset

In [120]:
# Loading our files
# url = "http://bit.ly/autolib_dataset"

url = "http://bit.ly/autolib_dataset"


Autodf = pd.read_csv(url)


In [245]:
Autodf.shape

(5000, 21)

#1.21 Previewing our dataset

In [121]:
Autodf.head()

Address  Cars  Bluecar counter  ...  day  hour  minute
0                 2 Avenue de Suffren     0                0  ...    8    11      43
1           145 Rue Raymond Losserand     6                6  ...    6     7      24
2    2 Avenue John Fitzgerald Kennedy     3                3  ...    3    20      14
3              51 Rue EugÃ¨ne OudinÃ©     3                3  ...    4     4      37
4  6 avenue de la Porte de Champerret     3                3  ...    8    17      23

[5 rows x 25 columns]

#1.3 Cleaning the dataset

###1.30 We first check for dataset information to get to know more about the dataset

In [122]:
Autodf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 25 columns):
 #   Column               Non-Null Count  Dtype 
---  ------               --------------  ----- 
 0   Address              5000 non-null   object
 1   Cars                 5000 non-null   int64 
 2   Bluecar counter      5000 non-null   int64 
 3   Utilib counter       5000 non-null   int64 
 4   Utilib 1.4 counter   5000 non-null   int64 
 5   Charge Slots         5000 non-null   int64 
 6   Charging Status      5000 non-null   object
 7   City                 5000 non-null   object
 8   Displayed comment    111 non-null    object
 9   ID                   5000 non-null   object
 10  Kind                 5000 non-null   object
 11  Geo point            5000 non-null   object
 12  Postal code          5000 non-null   int64 
 13  Public name          5000 non-null   object
 14  Rental status        5000 non-null   object
 15  Scheduled at         47 non-null     object
 16  Slots 

##1.31 Checking column names

In [123]:
Autodf.columns

Index(['Address', 'Cars', 'Bluecar counter', 'Utilib counter',
       'Utilib 1.4 counter', 'Charge Slots', 'Charging Status', 'City',
       'Displayed comment', 'ID', 'Kind', 'Geo point', 'Postal code',
       'Public name', 'Rental status', 'Scheduled at', 'Slots', 'Station type',
       'Status', 'Subscription status', 'year', 'month', 'day', 'hour',
       'minute'],
      dtype='object')

## 1.32 Checking for duplicates

In [124]:
Autodf.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...  
4995    False
4996    False
4997    False
4998    False
4999    False
Length: 5000, dtype: bool

### There are no duplicates

##1.33 Checking for missing values

In [125]:
Autodf.isnull().sum()

Address                   0
Cars                      0
Bluecar counter           0
Utilib counter            0
Utilib 1.4 counter        0
Charge Slots              0
Charging Status           0
City                      0
Displayed comment      4889
ID                        0
Kind                      0
Geo point                 0
Postal code               0
Public name               0
Rental status             0
Scheduled at           4953
Slots                     0
Station type              0
Status                    0
Subscription status       0
year                      0
month                     0
day                       0
hour                      0
minute                    0
dtype: int64

There are missing values in the 'Displayed comment' column and the 'Subscription status' column

##1.34 Dropping columns with too many missing values.

In [ ]:
# dropping the 'Displayed comment' column
 
#Autodf.drop('Displayed comment', inplace=True, axis=1)


In [130]:
# dropping 'Scheduled at' column

Autodf.drop('Scheduled at', inplace=True, axis=1)

##1.35 Dropping the column 'Cars' since we dont need it for this analysis

In [145]:
# dropping column named 'Cars
 

#Autodf.drop('Cars', inplace=True, axis=1)


In [147]:
#previewing
Autodf.head(2)

Address  Bluecar counter  ...  hour  minute
0        2 Avenue de Suffren                0  ...    11      43
1  145 Rue Raymond Losserand                6  ...     7      24

[2 rows x 22 columns]

In [148]:
#previewing
### Checking the column names 

Autodf.columns

Index(['Address', 'Bluecar counter', 'Utilib counter', 'Utilib 1.4 counter',
       'Charge Slots', 'Charging Status', 'City', 'ID', 'Kind', 'Geo point',
       'Postal code', 'Public name', 'Rental status', 'Slots', 'Station type',
       'Status', 'Subscription status', 'year', 'month', 'day', 'hour',
       'minute'],
      dtype='object')

## 1.4 combining year, month, day into Date and hour & minute into time

In [87]:
# First, we import datetime from datetime

from datetime import datetime
from datetime import date


In [150]:
# Then  we combine the columns 'year','month','day'

Autodf['date']=pd.to_datetime(Autodf[['year','month','day']])


# previewing the dataframe
Autodf.head(2)

Address  Bluecar counter  ...  minute       date
0        2 Avenue de Suffren                0  ...      43 2018-04-08
1  145 Rue Raymond Losserand                6  ...      24 2018-04-06

[2 rows x 23 columns]

## 1.5 Dropping the year, month, day columns from the dataframe

In [153]:
# dropping the columns

#Autodf.drop(columns=['year', 'month', 'day'], inplace= True, axis = 1)



# Checking the column names
Autodf.columns

Index(['Address', 'Bluecar counter', 'Utilib counter', 'Utilib 1.4 counter',
       'Charge Slots', 'Charging Status', 'City', 'ID', 'Kind', 'Geo point',
       'Postal code', 'Public name', 'Rental status', 'Slots', 'Station type',
       'Status', 'Subscription status', 'hour', 'minute', 'date'],
      dtype='object')

In [154]:
# Previewing the dataframe after dropping thes columns

Autodf.head(2)

Address  Bluecar counter  ...  minute       date
0        2 Avenue de Suffren                0  ...      43 2018-04-08
1  145 Rue Raymond Losserand                6  ...      24 2018-04-06

[2 rows x 20 columns]

##1.6 Dropping uneccessary rows

##1.7 Editing column names of the new dataframe

In [155]:
# We edit/ clean the column names

Autodf.columns = Autodf.columns.str.strip().str.lower().str.replace(' ', '_').str.replace('(', '').str.replace(')', '')
Autodf.head(2)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  This is separate from the ipykernel package so we can avoid doing imports until


address  bluecar_counter  ...  minute       date
0        2 Avenue de Suffren                0  ...      43 2018-04-08
1  145 Rue Raymond Losserand                6  ...      24 2018-04-06

[2 rows x 20 columns]

###1.8 Dropping unnecessary rows

In [157]:
 # we select only rows where status is not scheduled 
 
#df2 = df1[df1.Status != 'scheduled']
#df2

#Autodf[Autodf.Status != 'scheduled']
Autodf.shape

(5000, 20)

In [244]:
# cheking columns

Autodf.columns

Index(['address', 'bluecar', 'utilib', 'utilib_1.4', 'charge_slots',
       'charging_status', 'city', 'id', 'kind', 'geo_point', 'postal_code',
       'station_name', 'rental_status', 'slots', 'station_type', 'status',
       'subscription_status', 'hour', 'minute', 'date', 'total_cars'],
      dtype='object')

summing the total number of cars

In [164]:
# we sum the total number of cars
total_cars = Autodf["bluecar_counter"] + Autodf["utilib_counter"] + Autodf["utilib_1.4_counter"] 
Autodf["total_cars"] = total_cars


# Checking the changes
Autodf.head(2)

address  bluecar_counter  ...       date  total_cars
0        2 Avenue de Suffren                0  ... 2018-04-08           0
1  145 Rue Raymond Losserand                6  ... 2018-04-06           6

[2 rows x 21 columns]

##1.9 We Rename 'Public name' column to 'Station Name' and remove the word counter from Bluecar counter, Utilib counter and Utilib 1.4 counter

In [169]:
Autodf = Autodf.rename(columns = {'public_name':'station_name', 'bluecar_counter':'bluecar', 'utilib_counter':'utilib', 'utilib_1.4_counter': 'utilib_1.4'})

# previewing
Autodf.head(2)

address  bluecar  utilib  ...  minute       date total_cars
0        2 Avenue de Suffren        0       0  ...      43 2018-04-08          0
1  145 Rue Raymond Losserand        6       0  ...      24 2018-04-06          6

[2 rows x 21 columns]

##1.91 Grouping the station names with the specific postal codes

In [172]:
grouped_Autodf = Autodf.groupby(["postal_code", "station_name"]).size()
grouped_Autodf

postal_code  station_name                   
75001        Paris/Amiral Coligny/2             3
             Paris/Bertin PoirÃ©e/14            6
             Paris/Colonel Driant/7             4
             Paris/Croix des Petits Champs/4    6
             Paris/Halles/3                     4
                                               ..
95870        Bezons/Edouard Vaillant/77         4
             Bezons/Emile Zola/50               6
             Bezons/Jean JaurÃ¨s/81             3
95880        Enghien-les-Bains/ArrivÃ©e/19      6
             Enghien-les-Bains/Coussaye/2       4
Length: 1105, dtype: int64

## 1.92Check whether the dates in the data set are within the required period. 
#####This is anytime in April (April 1 to April 30 2018)

In [175]:
mask = (Autodf['date'] > '2018-04-01') & (Autodf['date'] <= '2018-04-30')
print(Autodf.loc[mask])

                                 address  bluecar  ...       date  total_cars
0                    2 Avenue de Suffren        0  ... 2018-04-08           0
1              145 Rue Raymond Losserand        6  ... 2018-04-06           6
2       2 Avenue John Fitzgerald Kennedy        3  ... 2018-04-03           5
3                 51 Rue EugÃ¨ne OudinÃ©        3  ... 2018-04-04           4
4     6 avenue de la Porte de Champerret        3  ... 2018-04-08           3
...                                  ...      ...  ...        ...         ...
4993          6 avenue Charles-de-Gaulle        6  ... 2018-04-02           6
4995                 8 avenue MÃ©nelotte        2  ... 2018-04-06           2
4996                   37 rue de Dantzig        4  ... 2018-04-04           4
4998         2 avenue du Val de Fontenay        2  ... 2018-04-04           2
4999                 5 Rue Henry Brisson        4  ... 2018-04-08           4

[4416 rows x 21 columns]


In [177]:
mask.shape

(5000,)

#####The dates given are within the month of April 2018

#2.1 Data Analysis

In [179]:
# Let us preview ou dataset

Autodf.head()

address  bluecar  ...       date  total_cars
0                 2 Avenue de Suffren        0  ... 2018-04-08           0
1           145 Rue Raymond Losserand        6  ... 2018-04-06           6
2    2 Avenue John Fitzgerald Kennedy        3  ... 2018-04-03           5
3              51 Rue EugÃ¨ne OudinÃ©        3  ... 2018-04-04           4
4  6 avenue de la Porte de Champerret        3  ... 2018-04-08           3

[5 rows x 21 columns]

##2.2Questions

####2.21 What was the most popular hour of the day for picking up a shared electric car (Bluecar) in the city of Paris over the month of April 2018

In [181]:
#What was the most popular hour of the day 
#for picking up a shared electric car (Bluecar) in the city of Paris over the month of April 2018.


Paris = Autodf[(Autodf['city']== 'Paris') & (Autodf['rental_status'] == 'operational')]
Autodf.groupby('hour')['bluecar'].value_counts().sort_values(ascending=False).head(1)

hour  bluecar
14    0          76
Name: bluecar, dtype: int64

The most popular hour was 1400hrs 

#####2.22 What is the most popular hour for returning cars?

In [183]:
# What is the most popular hour for returning cars?

Autodf.groupby('hour')['slots'].sum().sort_values(ascending=True).head(1) 



hour
17    349
Name: slots, dtype: int64

1700hours is seen to be the most popular hour for returning cars since the parking slots are fewer then.

####2.23 What station is most popular, overall?

In [186]:
##What station is most popular, overall?

Autodf.groupby('station_name')['total_cars'].sum().sort_values(ascending=True).head()

station_name
Alfortville/Blanqui/61        0
Paris/Ecole de Medecine/21    0
Paris/Etoile Foch/Parking     0
Paris/Flandre/61              0
Paris/FranÃ§ois 1er/38        0
Name: total_cars, dtype: int64

Alfortville//Blanqui/61 was the most popular station in the month of April 2018.

####2.24 The most popular station during the most popular picking hour

In [225]:
# The most popular station during the most popular picking hour

Autodf.groupby('station_name', 'hour' == 14)['total_cars'].sum().sort_values(ascending= False).head(5)


station_name
Fontenay-aux-Roses/Robert Marchand/32     50
Paris/Porte de Montrouge/8                50
Le Plessis-Robinson/GalilÃ©e/16           49
Fontenay-aux-Roses/Lombard/20             48
Fontenay-aux-Roses/Division Leclerc/31    46
Name: total_cars, dtype: int64

The most popular station during the most popular hour is Fontenay-aux-Roses/Robert Marchand/32

#### 2.25 Postal code that is the most popular for picking up Blue cars.

In [227]:
#Postal code that is the most popular for picking up Blue cars.

Autodf.groupby('postal_code')['bluecar'].sum().sort_values(ascending=False).head(2)


postal_code
75015    609
75016    595
Name: bluecar, dtype: int64

75015 is the most popular postal code for picking up blue cars

#### 2.26 Does the most popular station belong to that postal code

In [235]:
#Does the most popular station belong to that postal code


if 'station_name' == 'Fontenay-aux-Roses/Robert Marchand/32' and 'postal_code' == 75015:
  print("yes")
else:
  print("no")


no


the most popular station does not belong to that postal code

## 2.3 Checking for 'utilib'

####2.31 What was the most popular hour of the day for picking up a shared (utilib) in the city of Paris over the month of April 2018.


In [236]:
#What was the most popular hour of the day 
#for picking up a shared (utilib) in the city of Paris over the month of April 2018.


Paris = Autodf[(Autodf['city']== 'Paris') & (Autodf['rental_status'] == 'operational')]
Autodf.groupby('hour')['utilib'].value_counts().sort_values(ascending=False).head(1)

hour  utilib
21    0         225
Name: utilib, dtype: int64

Most popular hour of the day for picking up utilib is 2100hrs

####2.32 Postal code that is the most popular for picking up Utilib

In [238]:
#Postal code that is the most popular for picking up utilib.

Autodf.groupby('postal_code')['utilib'].sum().sort_values(ascending=False).head(2)


postal_code
75016    20
75017    20
Name: utilib, dtype: int64

Postal code that is most popular for picking up utilib is 75016

In [239]:
#Does the most popular station belong to that postal code


if 'station_name' == 'Fontenay-aux-Roses/Robert Marchand/32' and 'postal_code' == 75016:
  print("yes")
else:
  print("no")


no


##2.4 checking for utilib_1**.4**

#####2.41 What was the most popular hour of the day for picking up a shared utilib_1.4 in the city of Paris over the month of April 2018

In [240]:
#What was the most popular hour of the day 
#for picking up a shared electric car (Bluecar) in the city of Paris over the month of April 2018.


Paris = Autodf[(Autodf['city']== 'Paris') & (Autodf['rental_status'] == 'operational')]
Autodf.groupby('hour')['utilib_1.4'].value_counts().sort_values(ascending=False).head(1)

hour  utilib_1.4
21    0             214
Name: utilib_1.4, dtype: int64

The most popular hour for picking up utilib_1.4 is 2100hours

#### 2.42 Postal code that is the most popular for picking up utilib_1.4.

In [242]:
#Postal code that is the most popular for picking up utilib.

Autodf.groupby('postal_code')['utilib_1.4'].sum().sort_values(ascending=False).head(2)


postal_code
75017    40
75015    34
Name: utilib_1.4, dtype: int64

Postal code that is the most popular for picking up utilib is 75017

##### 2.43 Does the most popular station belong to that postal code

In [243]:
#Does the most popular station belong to that postal code


if 'station_name' == 'Fontenay-aux-Roses/Robert Marchand/32' and 'postal_code' == 75017:
  print("yes")
else:
  print("no")

no


The most popular station does not belong to that postal code